version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - db
      - redis
    networks:
      - evolution_network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: evolution_user
      POSTGRES_PASSWORD: evolution_pass
      POSTGRES_DB: evolution
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - evolution_network

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - evolution_network

volumes:
  evolution_instances:
  db_data:
  redis_data:

networks:
  evolution_network:
