services:
  - type: web
    name: evolution-api
    env: docker
    dockerImage: atendai/evolution-api:v2.1.1
    plan: standard
    disk:
      name: evolution-instances
      mountPath: /evolution/instances
      sizeGB: 1
    envVars:
      # Environment variables from .env file
      # Replace with actual key-value pairs from your .env file
      - key: KEY_FROM_ENV
        value: VALUE_FROM_ENV

      # Database connection string
      - key: DATABASE_URL
        fromDatabase:
          name: evolution-db
          property: connectionString

      # Redis connection string
      - key: REDIS_URL
        fromDatabase:
          name: evolution-redis
          property: connectionString

databases:
  - name: evolution-db
    databaseName: evolution
    user: evolution_user
    password: evolution_pass
    plan: standard
    postgresVersion: 13

  - name: evolution-redis
    plan: standard
    redisVersion: 6
